Add option to support custom http client
bold-commerce/go-shopify pull request #130
Opened 2020-12-07 21:32 UTC by fidel-ruiz

- add WithHTTPClient as an option

2020-12-07 21:39 UTC, sandersjessica commented
Looks good to me!

2020-12-07 21:52 UTC, joshsimard requested changes

2020-12-07 21:52 UTC, joshsimard commented on options.go
> +// WithHTTPClient allows to set a custom http client
`WithHTTPClient is used to set a custom http client` would sound better. `allows to` isn't the best choice in my opinion

2020-12-07 21:53 UTC, ysurtayev-bold approved these changes

2020-12-07 22:00 UTC, BoldBrandonM submitted a review, later dismissed

2020-12-08 02:53 UTC, joshsimard approved these changes

2020-12-08 19:58 UTC, ysurtayev-bold submitted a review, later dismissed

2020-12-08 20:00 UTC, gordcurrie approved these changes
Looks good to me

2020-12-08 20:36 UTC, gcfresh approved these changes
Looks good to me

2020-12-09 14:42 UTC, gordcurrie approved these changes
Approving again as not the checks weren't getting triggered and @fidel-ruiz had to `git commit --amend` to trigger them to run again.

2020-12-09 14:42 UTC, merged